version: '3.4'
services:
  # These are backend services that the app depends on
  db:
    image: postgres:9.6.13-alpine
    ports:
      - "54320:5432"
  redis:
    image: redis:5.0-alpine
    command: redis-server
    logging:
      driver: none
  # These are the components of the app
  app:
    build:
      context: .
      args:
        UID: ${UID:-1001}
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
    entrypoint: ["bin/docker_start.sh"]

